### ISSUE TITLE
Exit codes

### ISSUE THREAD

**Issue by xaduha** [KnicKnic/go-powershell#13]
Hi, is there an official way to get an exit code or something like that? Gonna try explicitly printing $LASTEXITCODE, but seems like a crutch.

**Comment by KnicKnic** [comment]
If you had a function that called a executable and you wanted the exit code of that executable from the powershell function you would return it.  This would allow the function to abstract what you were doing.

Since this project allows you to make calls into powershell, you would logically do the same thing. Emit the $LASTEXITCODE, or store it in a value and then emit it from the powershell.

Then in the go, you can inspect that emitted object.
